apiVersion: storage.coreos.com/v1alpha1
kind: StorageCluster
metadata:
    name: gluster
spec:
    type: glusterfs
    storageNodes:
        - nodeName: ip-10-0-32-78.us-west-1.compute.internal
          storageNetwork:
            ips:
                - 10.0.32.78
          devices:
              - /dev/xvdc
              - /dev/xvdd
              - /dev/xvde
          glusterfs:
              zone: 1
        - nodeName: ip-10-0-33-229.us-west-1.compute.internal
          storageNetwork:
            ips:
                - 10.0.33.229
          devices:
              - /dev/xvdc
              - /dev/xvdd
              - /dev/xvde
          glusterfs:
              zone: 1
        - nodeName: ip-10-0-49-32.us-west-1.compute.internal
          storageNetwork:
            ips:
                - 10.0.49.32
          devices:
              - /dev/xvdc
              - /dev/xvdd
              - /dev/xvde
          glusterfs:
              zone: 2
        - nodeName: ip-10-0-55-197.us-west-1.compute.internal
          storageNetwork:
            ips:
                - 10.0.55.197
          devices:
              - /dev/xvdc
              - /dev/xvdd
              - /dev/xvde
          glusterfs:
              zone: 2
